"""initial_schema

Revision ID: b117e695ca6d
Revises: 
Create Date: 2026-09-28 17:01:55.166629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b117e695ca6d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_dataset',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('dataset_type', sa.String(length=16), nullable=False),
    sa.Column('train_scene', sa.String(length=32), nullable=True),
    sa.Column('train_method', sa.String(length=16), nullable=True),
    sa.Column('storage_location', sa.String(length=16), nullable=False),
    sa.Column('import_method', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_eval_dimension',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('eval_type', sa.String(length=32), nullable=False),
    sa.Column('eval_config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_leaderboard',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('dimension_ids', sa.JSON(), nullable=False),
    sa.Column('dimension_names', sa.JSON(), nullable=False),
    sa.Column('task_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_model',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('base_model', sa.String(length=128), nullable=False),
    sa.Column('train_method', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('bucket', sa.String(length=128), nullable=False),
    sa.Column('model_dir', sa.String(length=512), nullable=False),
    sa.Column('provider_config', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('api_type', sa.String(length=16), nullable=False),
    sa.Column('api_base', sa.String(length=500), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_names', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_config',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('space_id', sa.String(length=40), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('knowledge_space',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_space_user_id'), 'knowledge_space', ['user_id'], unique=False)
    op.create_table('ml_dataset_version',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('dataset_id', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('data_count', sa.Integer(), nullable=False),
    sa.Column('import_status', sa.String(length=16), nullable=False),
    sa.Column('publish_status', sa.String(length=16), nullable=False),
    sa.Column('file_id', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('preview_content', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['ml_dataset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_dataset_version_dataset_id'), 'ml_dataset_version', ['dataset_id'], unique=False)
    op.create_table('ml_eval_task',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('model_id', sa.String(length=40), nullable=True),
    sa.Column('model_type', sa.String(length=16), nullable=False),
    sa.Column('llm_model_id', sa.String(length=40), nullable=True),
    sa.Column('data_source', sa.String(length=16), nullable=False),
    sa.Column('data_id', sa.String(length=40), nullable=False),
    sa.Column('data_mode', sa.String(length=16), nullable=False),
    sa.Column('split_dataset_id', sa.String(length=40), nullable=False),
    sa.Column('split_ratio', sa.Float(), nullable=False),
    sa.Column('dimension_ids', sa.JSON(), nullable=False),
    sa.Column('dimension_names', sa.JSON(), nullable=False),
    sa.Column('sync_leaderboard', sa.Boolean(), nullable=False),
    sa.Column('leaderboard_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['leaderboard_id'], ['ml_leaderboard.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['ml_model.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_eval_task_leaderboard_id'), 'ml_eval_task', ['leaderboard_id'], unique=False)
    op.create_index(op.f('ix_ml_eval_task_model_id'), 'ml_eval_task', ['model_id'], unique=False)
    op.create_index(op.f('ix_ml_eval_task_status'), 'ml_eval_task', ['status'], unique=False)
    op.create_table('ml_train_task',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=4), nullable=False),
    sa.Column('train_method', sa.String(length=16), nullable=False),
    sa.Column('base_model', sa.String(length=128), nullable=False),
    sa.Column('dataset_id', sa.String(length=40), nullable=True),
    sa.Column('valid_ratio', sa.Float(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('output_model_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('output_dir', sa.String(length=512), nullable=False),
    sa.Column('log', sa.Text(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['ml_dataset.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_train_task_dataset_id'), 'ml_train_task', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_ml_train_task_status'), 'ml_train_task', ['status'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('space_id', sa.String(length=40), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=16), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['space_id'], ['knowledge_space.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_space_id'), 'document', ['space_id'], unique=False)
    op.create_index(op.f('ix_document_status'), 'document', ['status'], unique=False)
    op.create_table('chunk',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('document_id', sa.String(length=40), nullable=False),
    sa.Column('space_id', sa.String(length=40), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('embedding_model', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunk_document_id'), 'chunk', ['document_id'], unique=False)
    op.create_index(op.f('ix_chunk_space_id'), 'chunk', ['space_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunk_space_id'), table_name='chunk')
    op.drop_index(op.f('ix_chunk_document_id'), table_name='chunk')
    op.drop_table('chunk')
    op.drop_index(op.f('ix_document_status'), table_name='document')
    op.drop_index(op.f('ix_document_space_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_ml_train_task_status'), table_name='ml_train_task')
    op.drop_index(op.f('ix_ml_train_task_dataset_id'), table_name='ml_train_task')
    op.drop_table('ml_train_task')
    op.drop_index(op.f('ix_ml_eval_task_status'), table_name='ml_eval_task')
    op.drop_index(op.f('ix_ml_eval_task_model_id'), table_name='ml_eval_task')
    op.drop_index(op.f('ix_ml_eval_task_leaderboard_id'), table_name='ml_eval_task')
    op.drop_table('ml_eval_task')
    op.drop_index(op.f('ix_ml_dataset_version_dataset_id'), table_name='ml_dataset_version')
    op.drop_table('ml_dataset_version')
    op.drop_index(op.f('ix_knowledge_space_user_id'), table_name='knowledge_space')
    op.drop_table('knowledge_space')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('system_config')
    op.drop_table('provider')
    op.drop_table('ml_model')
    op.drop_table('ml_leaderboard')
    op.drop_table('ml_eval_dimension')
    op.drop_table('ml_dataset')
    # ### end Alembic commands ###
